BEGIN;
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Gül', 'Gül — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 75.62, 14, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Lale', 'Lale — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 83.43, 8, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Papatya', 'Papatya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 47.97, 39, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Karanfil', 'Karanfil — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 50.35, 8, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Nergis', 'Nergis — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 140.07, 18, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Zambak', 'Zambak — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 44.12, 32, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Yasemin', 'Yasemin — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 86.0, 20, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Menekşe', 'Menekşe — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 49.98, 32, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Ortanca', 'Ortanca — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 46.5, 12, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Manolya', 'Manolya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 144.22, 8, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sardunya', 'Sardunya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 103.48, 30, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kasımpatı', 'Kasımpatı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 45.45, 19, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Begonvil', 'Begonvil — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 45.12, 13, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Petunya', 'Petunya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 71.86, 14, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Frezya', 'Frezya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 99.48, 24, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kadife Çiçeği', 'Kadife Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 101.63, 16, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Hercai Menekşe', 'Hercai Menekşe — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 51.34, 17, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Lavanta', 'Lavanta — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 80.96, 40, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Şebboy', 'Şebboy — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 118.33, 8, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kamelya', 'Kamelya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 108.09, 36, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('İris', 'İris — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 114.84, 32, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Krizantem', 'Krizantem — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 125.5, 34, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Gerbera', 'Gerbera — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 104.41, 34, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Aslanağzı', 'Aslanağzı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 79.77, 20, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Ayçiçeği', 'Ayçiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 127.38, 20, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Gelincik', 'Gelincik — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 49.0, 24, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Şakayık', 'Şakayık — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 97.77, 26, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Katmerli Gül', 'Katmerli Gül — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 120.24, 23, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Glayöl', 'Glayöl — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 106.99, 9, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Süsen', 'Süsen — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 52.99, 31, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kardelen', 'Kardelen — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 58.15, 26, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Zerrin', 'Zerrin — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 56.72, 36, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Akşamsefası', 'Akşamsefası — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 86.39, 9, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Horoz İbiği', 'Horoz İbiği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 124.1, 25, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Fesleğen Çiçeği', 'Fesleğen Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 77.41, 27, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kuşburnu Çiçeği', 'Kuşburnu Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 105.38, 34, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Manisa Lalesi', 'Manisa Lalesi — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 47.56, 10, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Anadolu Gelinciği', 'Anadolu Gelinciği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 143.91, 35, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Katmerli Karanfil', 'Katmerli Karanfil — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 116.67, 9, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sümbül', 'Sümbül — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 46.67, 24, 1, 2);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('İncir Kaktüsü (Kaktüs)', 'İncir Kaktüsü (Kaktüs) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 137.66, 33, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Noel Kaktüsü', 'Noel Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 94.15, 29, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Paskalya Kaktüsü', 'Paskalya Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 166.44, 27, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sarmaşık Kaktüsü', 'Sarmaşık Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 62.71, 34, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Küre Kaktüsü', 'Küre Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 102.66, 12, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Fıçı Kaktüs', 'Fıçı Kaktüs — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 119.24, 18, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Tavşankulağı Kaktüsü', 'Tavşankulağı Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 152.19, 13, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Yılan Kaktüsü', 'Yılan Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 148.6, 30, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Mum Kaktüsü', 'Mum Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 106.91, 36, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kirpi Kaktüsü', 'Kirpi Kaktüsü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 69.67, 33, 1, 3);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Aloe Vera', 'Aloe Vera — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 86.15, 22, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Jade Bitkisi (Para Ağacı)', 'Jade Bitkisi (Para Ağacı) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 129.5, 32, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Taşgülü (Echeveria)', 'Taşgülü (Echeveria) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 127.76, 22, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('İnci Dizisi', 'İnci Dizisi — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 113.58, 27, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kırlangıç Otu', 'Kırlangıç Otu — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 111.45, 29, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sedum', 'Sedum — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 136.2, 14, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kalanchoe', 'Kalanchoe — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 57.47, 14, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Haworthia', 'Haworthia — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 70.88, 19, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Semenderotu', 'Semenderotu — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 51.09, 16, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sukulent Karışım Saksı', 'Sukulent Karışım Saksı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 73.65, 5, 1, 4);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Areka Palmiyesi', 'Areka Palmiyesi — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 120.59, 39, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sedef Otu (Pothos)', 'Sedef Otu (Pothos) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 167.54, 25, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Yılan Bitkisi (Paşa Kılıcı)', 'Yılan Bitkisi (Paşa Kılıcı) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 290.15, 37, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Zamioculcas', 'Zamioculcas — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 289.55, 8, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Ficus Benjamina (Yalancı İncir)', 'Ficus Benjamina (Yalancı İncir) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 185.9, 40, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Barış Zambağı', 'Barış Zambağı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 172.4, 30, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Filodendron', 'Filodendron — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 172.77, 35, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Begonya', 'Begonya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 223.2, 8, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Anthurium', 'Anthurium — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 130.03, 18, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Devetabanı (Monstera)', 'Devetabanı (Monstera) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 182.53, 12, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Amerikan Sarmaşığı', 'Amerikan Sarmaşığı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 161.41, 8, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Örümcek Bitkisi', 'Örümcek Bitkisi — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 111.5, 14, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Difenbahya', 'Difenbahya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 202.69, 28, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Draçena', 'Draçena — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 218.88, 9, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kauçuk Ağacı', 'Kauçuk Ağacı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 273.61, 29, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Palmiye (İç Mekan)', 'Palmiye (İç Mekan) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 121.2, 21, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Aspidistra (Demir Bitkisi)', 'Aspidistra (Demir Bitkisi) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 290.65, 28, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kaktüs İncir Yaprağı', 'Kaktüs İncir Yaprağı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 189.57, 12, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Fesleğen (Saksı)', 'Fesleğen (Saksı) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 268.28, 34, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Nane (Saksı)', 'Nane (Saksı) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 190.88, 24, 1, 5);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Leylak', 'Leylak — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 130.06, 11, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Japon Süs Kirazı', 'Japon Süs Kirazı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 362.39, 21, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Hibiskus (Amber Çiçeği)', 'Hibiskus (Amber Çiçeği) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 267.52, 15, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Zakkum', 'Zakkum — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 280.72, 18, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Forsitya (Altın Çan Çiçeği)', 'Forsitya (Altın Çan Çiçeği) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 432.84, 38, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Orman Gülü', 'Orman Gülü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 226.61, 39, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Salkım Çiçeği (Mor Salkım)', 'Salkım Çiçeği (Mor Salkım) — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 419.95, 38, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Yasemin Sarmaşığı', 'Yasemin Sarmaşığı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 204.33, 10, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Sarmaşık Gülü', 'Sarmaşık Gülü — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 343.67, 21, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Manolya Ağacı', 'Manolya Ağacı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 281.44, 15, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Erguvan', 'Erguvan — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 224.49, 19, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Mimoza', 'Mimoza — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 286.41, 37, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Akasya', 'Akasya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 215.38, 19, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Katalpa', 'Katalpa — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 314.63, 17, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Ihlamur Çiçeği', 'Ihlamur Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 382.13, 30, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kestane Çiçeği', 'Kestane Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 358.96, 19, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Nar Çiçeği', 'Nar Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 169.97, 36, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Zeytin Ağacı Çiçeği', 'Zeytin Ağacı Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 224.45, 6, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Badem Çiçeği', 'Badem Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 446.36, 22, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Erik Çiçeği', 'Erik Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 265.28, 17, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kiraz Çiçeği', 'Kiraz Çiçeği — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 342.38, 27, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Söğüt', 'Söğüt — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 256.53, 27, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Boğaz Manolyası', 'Boğaz Manolyası — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 434.25, 28, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Kokulu Sardunya', 'Kokulu Sardunya — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 128.19, 11, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Duvar Sarmaşığı', 'Duvar Sarmaşığı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 179.4, 17, 1, 6);
INSERT INTO prod (name, description, price, stock, gnl_st_id, prod_spec_id) VALUES ('Katırtırnağı', 'Katırtırnağı — Türkiye''de yaygın olarak yetiştirilen, bakımı kolay bir bitki.', 218.21, 35, 1, 6);
COMMIT;
