"""Add complaint table

Revision ID: 20580caf4501
Revises: a65f19f543dd
Create Date: 2026-07-17 09:52:34.162764

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20580caf4501'
down_revision: str | None = 'a65f19f543dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complaint_type', sa.String(length=50), nullable=False),
    sa.Column('cust_ord_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('reported_seller_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('admin_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_ord_id'], ['cust_ord.cust_ord_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_seller_id'], ['app_user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.drop_index('ix_prod_owner_user_id', table_name='prod')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_prod_owner_user_id', 'prod', ['owner_user_id'], unique=False)
    op.drop_table('complaint')
    # ### end Alembic commands ###
