"""Add AI fields to complaint

Revision ID: 691dea865e88
Revises: 20580caf4501
Create Date: 2026-07-17 10:11:14.697282

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '691dea865e88'
down_revision: str | None = '20580caf4501'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('sentiment', sa.String(length=30), nullable=True))
    op.add_column('complaint', sa.Column('urgency', sa.String(length=30), nullable=True))
    op.add_column('complaint', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('complaint', sa.Column('ai_tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'ai_tags')
    op.drop_column('complaint', 'ai_summary')
    op.drop_column('complaint', 'urgency')
    op.drop_column('complaint', 'sentiment')
    # ### end Alembic commands ###
