"""add customer product model

Revision ID: a133121ab87f
Revises: da88b41fbac1
Create Date: 2026-07-22 16:15:17.852988

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a133121ab87f'
down_revision: str | None = 'da88b41fbac1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cust_prod',
    sa.Column('cust_prod_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('prod_spec_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('watering_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_watered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prod_spec_id'], ['prod_spec.prod_spec_id'], ),
    sa.PrimaryKeyConstraint('cust_prod_id')
    )
    op.add_column('bsn_inter', sa.Column('prod_id', sa.Integer(), nullable=False))
    op.add_column('bsn_inter', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('bsn_inter_bsn_inter_spec_id_fkey', 'bsn_inter', type_='foreignkey')
    op.create_foreign_key(None, 'bsn_inter', 'prod', ['prod_id'], ['prod_id'])
    op.drop_column('bsn_inter', 'cdate')
    op.drop_column('bsn_inter', 'bsn_inter_spec_id')
    op.drop_column('bsn_inter', 'sale_cnl_id')
    op.add_column('bsn_inter_spec', sa.Column('bsn_inter_id', sa.Integer(), nullable=False))
    op.add_column('bsn_inter_spec', sa.Column('action_type', sa.String(length=50), nullable=False))
    op.add_column('bsn_inter_spec', sa.Column('action_value', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'bsn_inter_spec', 'bsn_inter', ['bsn_inter_id'], ['bsn_inter_id'], ondelete='CASCADE')
    op.drop_column('bsn_inter_spec', 'is_actv')
    op.drop_column('bsn_inter_spec', 'cdate')
    op.drop_column('bsn_inter_spec', 'description')
    op.drop_column('bsn_inter_spec', 'name')
    op.drop_column('bsn_inter_spec', 'shrt_code')
    op.drop_constraint('unique_post_user_like', 'community_like', type_='unique')
    op.drop_index('idx_customer_address_cust_id', table_name='customer_address')
    op.drop_column('gnl_st', 'entity_code')
    op.drop_index('idx_ilce_il_id', table_name='ilce')
    op.drop_index('idx_mahalle_ilce_id', table_name='mahalle')
    op.alter_column('prod', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_prod_is_active', table_name='prod')
    op.drop_constraint('uq_review_user_cust_ord_item', 'review', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_cust_ord_item', 'review', ['user_id', 'cust_ord_item_id'])
    op.create_index('idx_prod_is_active', 'prod', ['is_active'], unique=False)
    op.alter_column('prod', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('idx_mahalle_ilce_id', 'mahalle', ['ilce_id'], unique=False)
    op.create_index('idx_ilce_il_id', 'ilce', ['il_id'], unique=False)
    op.add_column('gnl_st', sa.Column('entity_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_customer_address_cust_id', 'customer_address', ['cust_id'], unique=False)
    op.create_unique_constraint('unique_post_user_like', 'community_like', ['post_id', 'user_id'])
    op.add_column('bsn_inter_spec', sa.Column('shrt_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bsn_inter_spec', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bsn_inter_spec', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bsn_inter_spec', sa.Column('cdate', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('bsn_inter_spec', sa.Column('is_actv', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bsn_inter_spec', type_='foreignkey')
    op.drop_column('bsn_inter_spec', 'action_value')
    op.drop_column('bsn_inter_spec', 'action_type')
    op.drop_column('bsn_inter_spec', 'bsn_inter_id')
    op.add_column('bsn_inter', sa.Column('sale_cnl_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('bsn_inter', sa.Column('bsn_inter_spec_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='bsn_inter_spec foreign key'))
    op.add_column('bsn_inter', sa.Column('cdate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bsn_inter', type_='foreignkey')
    op.create_foreign_key('bsn_inter_bsn_inter_spec_id_fkey', 'bsn_inter', 'bsn_inter_spec', ['bsn_inter_spec_id'], ['bsn_inter_spec_id'], onupdate='CASCADE')
    op.drop_column('bsn_inter', 'created_at')
    op.drop_column('bsn_inter', 'prod_id')
    op.drop_table('cust_prod')
    # ### end Alembic commands ###
