
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a57119a8b471'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_firebase_uid'), 'app_user', ['firebase_uid'], unique=True)
    op.create_table('gnl_char',
    sa.Column('gnl_char_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('gnl_char_id')
    )
    op.create_table('gnl_st',
    sa.Column('gnl_st_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('gnl_st_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('prod_spec',
    sa.Column('prod_spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('prod_spec_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('rsrc',
    sa.Column('rsrc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rsrc_id')
    )
    op.create_table('sale_cnl',
    sa.Column('sale_cnl_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('sale_cnl_id')
    )
    op.create_table('sch_job',
    sa.Column('sch_job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sch_job_id')
    )
    op.create_table('wrk_org',
    sa.Column('wrk_org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wrk_org_id')
    )
    op.create_table('ai_chat',
    sa.Column('ai_chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_chat_id')
    )
    op.create_table('ai_image_analysis',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('cust',
    sa.Column('cust_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_table('gnl_char_val',
    sa.Column('gnl_char_val_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gnl_char_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['gnl_char_id'], ['gnl_char.gnl_char_id'], ),
    sa.PrimaryKeyConstraint('gnl_char_val_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('prod',
    sa.Column('prod_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('gnl_st_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gnl_st_id'], ['gnl_st.gnl_st_id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('rsrc_spec',
    sa.Column('rsrc_spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rsrc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rsrc_id'], ['rsrc.rsrc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rsrc_spec_id')
    )
    op.create_table('srvc',
    sa.Column('srvc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gnl_st_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gnl_st_id'], ['gnl_st.gnl_st_id'], ),
    sa.PrimaryKeyConstraint('srvc_id')
    )
    op.create_table('user_role',
    sa.Column('user_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_table('ai_message',
    sa.Column('ai_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_chat_id'], ['ai_chat.ai_chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_message_id')
    )
    op.create_table('ai_recommendation',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('bsn_inter',
    sa.Column('bsn_inter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ),
    sa.PrimaryKeyConstraint('bsn_inter_id')
    )
    op.create_table('cust_acct',
    sa.Column('cust_acct_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cust_acct_id'),
    sa.UniqueConstraint('account_no')
    )
    op.create_table('cust_ord',
    sa.Column('cust_ord_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('sale_cnl_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gnl_st_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ),
    sa.ForeignKeyConstraint(['gnl_st_id'], ['gnl_st.gnl_st_id'], ),
    sa.ForeignKeyConstraint(['sale_cnl_id'], ['sale_cnl.sale_cnl_id'], ),
    sa.PrimaryKeyConstraint('cust_ord_id')
    )
    op.create_table('ind',
    sa.Column('ind_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('tc_no', sa.String(length=11), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ind_id')
    )
    op.create_table('org',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('tax_office', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['cust.cust_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('prod_char_val',
    sa.Column('prod_char_val_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_spec_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_val_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gnl_char_id'], ['gnl_char.gnl_char_id'], ),
    sa.ForeignKeyConstraint(['gnl_char_val_id'], ['gnl_char_val.gnl_char_val_id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prod_spec_id'], ['prod_spec.prod_spec_id'], ),
    sa.PrimaryKeyConstraint('prod_char_val_id')
    )
    op.create_table('prod_ofr',
    sa.Column('prod_ofr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prod_ofr_id')
    )
    op.create_table('srvc_spec',
    sa.Column('srvc_spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('srvc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['srvc_id'], ['srvc.srvc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('srvc_spec_id')
    )
    op.create_table('user_preference',
    sa.Column('preference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_val_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gnl_char_id'], ['gnl_char.gnl_char_id'], ),
    sa.ForeignKeyConstraint(['gnl_char_val_id'], ['gnl_char_val.gnl_char_val_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('ai_feedback',
    sa.Column('ai_feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_message_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ai_message_id'], ['ai_message.ai_message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_feedback_id')
    )
    op.create_table('bsn_inter_spec',
    sa.Column('bsn_inter_spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bsn_inter_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bsn_inter_id'], ['bsn_inter.bsn_inter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bsn_inter_spec_id')
    )
    op.create_table('cust_ord_char_val',
    sa.Column('cust_ord_char_val_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_ord_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cust_ord_id'], ['cust_ord.cust_ord_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gnl_char_id'], ['gnl_char.gnl_char_id'], ),
    sa.PrimaryKeyConstraint('cust_ord_char_val_id')
    )
    op.create_table('cust_ord_item',
    sa.Column('cust_ord_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_ord_id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cust_ord_id'], ['cust_ord.cust_ord_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prod_id'], ['prod.prod_id'], ),
    sa.PrimaryKeyConstraint('cust_ord_item_id')
    )
    op.create_table('cust_ord_item_char_val',
    sa.Column('cust_ord_item_char_val_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_ord_item_id', sa.Integer(), nullable=False),
    sa.Column('gnl_char_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cust_ord_item_id'], ['cust_ord_item.cust_ord_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gnl_char_id'], ['gnl_char.gnl_char_id'], ),
    sa.PrimaryKeyConstraint('cust_ord_item_char_val_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cust_ord_item_char_val')
    op.drop_table('cust_ord_item')
    op.drop_table('cust_ord_char_val')
    op.drop_table('bsn_inter_spec')
    op.drop_table('ai_feedback')
    op.drop_table('user_preference')
    op.drop_table('srvc_spec')
    op.drop_table('prod_ofr')
    op.drop_table('prod_char_val')
    op.drop_table('org')
    op.drop_table('ind')
    op.drop_table('cust_ord')
    op.drop_table('cust_acct')
    op.drop_table('bsn_inter')
    op.drop_table('ai_recommendation')
    op.drop_table('ai_message')
    op.drop_table('user_role')
    op.drop_table('srvc')
    op.drop_table('rsrc_spec')
    op.drop_table('prod')
    op.drop_table('notification')
    op.drop_table('gnl_char_val')
    op.drop_table('cust')
    op.drop_table('ai_image_analysis')
    op.drop_table('ai_chat')
    op.drop_table('wrk_org')
    op.drop_table('sch_job')
    op.drop_table('sale_cnl')
    op.drop_table('rsrc')
    op.drop_table('role')
    op.drop_table('prod_spec')
    op.drop_table('gnl_st')
    op.drop_table('gnl_char')
    op.drop_index(op.f('ix_app_user_firebase_uid'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
