"""expand customer product with logs

Revision ID: e1b02d5965d7
Revises: a133121ab87f
Create Date: 2026-07-22 16:38:09.905073

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e1b02d5965d7'
down_revision: str | None = 'a133121ab87f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cust_prod_care_log',
    sa.Column('care_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_prod_id', sa.Integer(), nullable=False),
    sa.Column('care_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_prod_id'], ['cust_prod.cust_prod_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('care_log_id')
    )
    op.create_table('cust_prod_growth_log',
    sa.Column('growth_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_prod_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cust_prod_id'], ['cust_prod.cust_prod_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('growth_log_id')
    )
    op.add_column('cust_prod', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('cust_prod', sa.Column('fertilizing_interval_days', sa.Integer(), nullable=True))
    op.add_column('cust_prod', sa.Column('last_fertilized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cust_prod', sa.Column('repotting_interval_days', sa.Integer(), nullable=True))
    op.add_column('cust_prod', sa.Column('last_repotted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cust_prod', 'last_repotted_at')
    op.drop_column('cust_prod', 'repotting_interval_days')
    op.drop_column('cust_prod', 'last_fertilized_at')
    op.drop_column('cust_prod', 'fertilizing_interval_days')
    op.drop_column('cust_prod', 'location')
    op.drop_table('cust_prod_growth_log')
    op.drop_table('cust_prod_care_log')
    # ### end Alembic commands ###
