"""create_all_tables

Revision ID: ffbc9d40f5f2
Revises: a57119a8b471
Create Date: 2026-07-13 15:31:16.826141

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ffbc9d40f5f2'
down_revision: str | None = 'a57119a8b471'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
